### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by fda1zt** [RenqiChen/Social_Science#2]
In your project's requirements.txt file, there is a line specifying agentscope=0.0.6a3=pypi_0. However, the official website does not provide this version of agentscope. How should this issue be resolved?

**Comment by RenqiChen** [comment]
Hello, just use the command `pip install agentscope` to install the agentscope is OK. In the requirement.txt, because our deployed environment is on the ARM architecture, then you cannot find this version.

**Comment by fda1zt** [comment]
Thanks！However，I am using Python 3.10 and have downloaded version 0.1.0 of `agentscope`, but I am getting the following error: `ImportError: cannot import name 'SciAgent' from 'agentscope.agents'`. How should this issue be resolved?

**Comment by RenqiChen** [comment]
Hello, SciAgent is in `agentscope-main/src/agentscope/agents/sci_agent.py`. Maybe you should set `sys.path.append('../agentscope-main/src')` (in `sci_platform/sci_platform.py`) correctly.

**Comment by RenqiChen** [comment]
In our experiments, we always run the program under the `sci_platform/` directory.

**Comment by fda1zt** [comment]
Thank you very much! The following libraries cannot find the corresponding versions:  
`apex==0.1`, `causal-conv1d==1.1.3`, `einops==0.7.0`, `etils==1.9.2`, `faiss==1.8.0`, `jaxlib==0.4.28+cuda12.cudnn89`. 

How should I resolve this? Do I need to upgrade my Python version?

**Comment by RenqiChen** [comment]
I think Python 3.10 is enough. In your listed libraries, the only useful library is `faiss`. You can download this freely. You do not need to use the same version.

**Comment by fda1zt** [comment]
Thank you for your patience in answering, but I still can't run it. How should I resolve this?
![WechatIMG62](https://github.com/user-attachments/assets/a575f4c3-27b9-4a35-abbd-e3f315133231)

**Comment by RenqiChen** [comment]
It is strange. I can run this correctly.
![image](https://github.com/user-attachments/assets/c012880b-9694-42be-ad29-57f6612b3d26)

**Comment by RenqiChen** [comment]
Do you follow the instructions of agentscope to install and deploy `ollama`?

**Comment by RenqiChen** [comment]
You could refer to this [website](https://github.com/modelscope/agentscope/blob/main/scripts/README.md#ollama) to configure the `ollama`.

**Comment by fda1zt** [comment]
Thanks, I have downloaded the **llama3.1** model using `ollama pull llama3.1` from your provided link. What should I do next? Should I use Flask?I would be immensely grateful if you could kindly guide me in your busy schedule. Thank you so much!

**Comment by jli113** [comment]
install faiss-gpu or faiss-cpu

**Comment by RenqiChen** [comment]
strongly recommend that you install faiss-gpu
