### ISSUE TITLE
How do I use Ollama in this project

### ISSUE THREAD

**Issue by fda1zt** [RenqiChen/Social_Science#3]
Thanks, I have downloaded the llama3.1 model using ollama pull llama3.1 from your provided link. What should I do next? Should I use Flask?I would be immensely grateful if you could kindly guide me in your busy schedule. Thank you so much!

**Comment by RenqiChen** [comment]
You should use `./ollama serve` to load your ollama model on an independent port. Then you can call your ollama model.

**Comment by fda1zt** [comment]
Thank you very much for your response. From which website or resources can I learn to implement the operations you mentioned?

**Comment by RenqiChen** [comment]
https://github.com/modelscope/agentscope/blob/main/scripts/README.md#ollama

**Comment by RenqiChen** [comment]
I think ollama website can help you to depoly this successfully.

**Comment by fda1zt** [comment]
Thank you very much. I will try it .
