### ISSUE TITLE
ollama serve 

### ISSUE THREAD

**Issue by fda1zt** [RenqiChen/Social_Science#4]
Sorry to bother you. I followed the link you provided, used the `ollama serve` command, then in another terminal, I entered `ollama run llama3.1`, and finally, in a third terminal, I ran `python run.py`. However, I encountered the same issue as before. Could you kindly provide a more detailed step-by-step guide whenever you have the time? Thank you for your help.
![图片](https://github.com/user-attachments/assets/ff64813d-a736-486c-bf3b-b17163cb8c9b)
![图片](https://github.com/user-attachments/assets/dcf0ff61-740c-48aa-97c4-0da084f895b3)
![图片](https://github.com/user-attachments/assets/35a2b0c2-da4f-4124-97af-b864806f8bab)

**Comment by RenqiChen** [comment]
Please follow this (website)[https://github.com/modelscope/agentscope/blob/main/scripts/README.md#ollama] and try to run the example code successfully first.

**Comment by KuKuKuKuKuKurisu** [comment]
Try `pip uninstall agentscope`? It seems the program is trying to load agentscope in the environment.

**Comment by ztlsky** [comment]
I have completed the example from the link. Could you provide a detailed tutorial?

**Comment by RenqiChen** [comment]
> Try `pip uninstall agentscope`? It seems the program is trying to load agentscope in the environment.

Maybe you can try this?

**Comment by ztlsky** [comment]
I have tried, but it returned this error.
![image](https://github.com/user-attachments/assets/98130c28-9431-4b33-a9dc-4c2996f6cbb2)

**Comment by KuKuKuKuKuKurisu** [comment]
The agentscope module is located in `agentscope-main/src/agentscope`. Just make sure this path is included in your working directory or in your Python path to resolve the ModuleNotFound error.

**Comment by fda1zt** [comment]
I have confirmed that the path is correct, and my error occurred because I uninstalled `agentscope` using `pip uninstall agentscope`. However, I still can't get it to run. Do you have a more detailed guide?

**Comment by KuKuKuKuKuKurisu** [comment]
I recommend testing if you can run agentscope, as agentscope-main was cloned directly from the [AgentScope GitHub Repo](https://github.com/modelscope/agentscope?tab=readme-ov-file). Navigate to cd agentscope-main, then create a test file containing the example provided in AgentScope's documentation and try running it.

**Comment by RenqiChen** [comment]
This issue is solved in #5
