### ISSUE TITLE
agentscope

### ISSUE THREAD

**Issue by NAMEKDSUN** [RenqiChen/Social_Science#5]
Traceback (most recent call last):
  File "/home/ecs-user/Social_Science/sci_platform/run.py", line 1, in <module>
    from sci_platform import Platform
  File "/home/ecs-user/Social_Science/sci_platform/sci_platform.py", line 13, in <module>
    from agentscope.agents import SciAgent
ImportError: cannot import name 'SciAgent' from 'agentscope.agents' (/home/ecs-user/anaconda3/envs/science/lib/python3.11/site-packages/agentscope/agents/__init__.py)
运行run.py文件报错，没有办法从项目中的agentscope导入SciAgent

**Comment by RenqiChen** [comment]
![image](https://github.com/user-attachments/assets/896b1c56-1bc9-4552-9bcd-b614b85c5ac0)

**Comment by RenqiChen** [comment]
这个是SciAgent所在的路径

**Comment by NAMEKDSUN** [comment]
![image](https://github.com/user-attachments/assets/46ea8e0c-01b3-4ca1-a834-2cce97f06114)
明白，我看代码中存在导入agentscope所在的文件路径，但是依然报ImportError: cannot import name 'SciAgent' from 'agentscope.agents' (/home/ecs-user/anaconda3/envs/science/lib/python3.11/site-packages/agentscope/agents/init.py)

**Comment by KuKuKuKuKuKurisu** [comment]
可以print一下sys.path吗

**Comment by NAMEKDSUN** [comment]
根据报错显示他并没有去项目中的agentscope寻找SciAgent，而是从使用pip install的agentscope寻找SciAgent

**Comment by NAMEKDSUN** [comment]
找到了解决办法，不要使用pip install agentscope来进行安装，使用开发者模型进行安装agentscope：pip install -e . ref：https://github.com/modelscope/agentscope/blob/main/README.md
![image](https://github.com/user-attachments/assets/170b99ce-6736-4085-98e7-c9c94fdce607)

**Comment by NAMEKDSUN** [comment]
我看您修改文档了，使用pip install -e.安装agentscope，必须要把agentscope的readme文档放在agentscope-main目录下才可以

**Comment by RenqiChen** [comment]
我们把setup.py里面这部分代码改掉了，尝试过可以正常安装

**Comment by JUNO523** [comment]
同学您好，想麻烦问下您是怎么安装的呀，是用服务器进行安装的嘛，是用的什么型号的呀

**Comment by JUNO523** [comment]
@NAMEKDSUN @KuKuKuKuKuKurisu 同学您好，想麻烦问下您是怎么安装的呀，是用服务器进行安装的嘛，是用的什么型号的呀

**Comment by KuKuKuKuKuKurisu** [comment]
我们是服务器那边的人帮我们装的，因为我们没有sudo权限，ollama的话按照这个步骤来操作就可以：
https://github.com/ollama/ollama-python
