### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by NAMEKDSUN** [RenqiChen/Social_Science#6]
我在代码中貌似看到了html，javascript相关的代码，那意味着该项目有可视化界面吗？如果有的话可否在readme中标注一下如何启动

**Comment by RenqiChen** [comment]
你好，因为这个框架是基于agentscope搭建的，所以里面会有agentscope本来的代码；目前还没有搭建可视化界面。

**Comment by NAMEKDSUN** [comment]
明白了谢谢
