### ISSUE TITLE
root_dir

### ISSUE THREAD

**Issue by NAMEKDSUN** [RenqiChen/Social_Science#7]
![image](https://github.com/user-attachments/assets/0a0b0158-3802-49a0-a46c-cde988c442ad)
root_dir存储的是什么文件呢，貌似没有提供

**Comment by RenqiChen** [comment]
你好，这个root_dir是我们自己实验用的是一个根目录，您可以自由更改这个路径，所有使用的文件都在Google Drive中，并且为了方便使用，名称都是和我们实验中的文件名是重合的。

**Comment by NAMEKDSUN** [comment]
![image](https://github.com/user-attachments/assets/56f543e9-86e0-4b30-89b8-4bfe20f6cc71)ke'shi可是我没在Google Drive中看到这个文件author2paper.json

**Comment by NAMEKDSUN** [comment]
好的，还有一些其他的文件也没有在Google Drive中看到比如agentID2authorID.json，我也简单注释掉吗

**Comment by RenqiChen** [comment]
可以的。

**Comment by NAMEKDSUN** [comment]
建议修改一下sci_platform文件，里面的路径需要修改的太多了，有些乱

**Comment by RenqiChen** [comment]
没问题的
